# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laserControl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12laserControl.proto\x12\x0claserControl\"\x17\n\x15GetLaserStatusRequest\"p\n\x16GetLaserStatusResponse\x12;\n\x06status\x18\x01 \x01(\x0e\x32+.laserControl.GetLaserStatusResponse.Status\"\x19\n\x06Status\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\"(\n\x15SetBiasVoltageRequest\x12\x0f\n\x07voltage\x18\x01 \x01(\x02\")\n\x16SetBiasVoltageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12\x45nableLaserRequest\"&\n\x13\x45nableLaserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x15\n\x13\x44isableLaserRequest\"\x16\n\x14\x44isableLaserResponse2\x82\x03\n\x13LaserControlService\x12]\n\x0eGetLaserStatus\x12#.laserControl.GetLaserStatusRequest\x1a$.laserControl.GetLaserStatusResponse\"\x00\x12]\n\x0eSetBiasVoltage\x12#.laserControl.SetBiasVoltageRequest\x1a$.laserControl.SetBiasVoltageResponse\"\x00\x12T\n\x0b\x45nableLaser\x12 .laserControl.EnableLaserRequest\x1a!.laserControl.EnableLaserResponse\"\x00\x12W\n\x0c\x44isableLaser\x12!.laserControl.DisableLaserRequest\x1a\".laserControl.DisableLaserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laserControl_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETLASERSTATUSREQUEST']._serialized_start=36
  _globals['_GETLASERSTATUSREQUEST']._serialized_end=59
  _globals['_GETLASERSTATUSRESPONSE']._serialized_start=61
  _globals['_GETLASERSTATUSRESPONSE']._serialized_end=173
  _globals['_GETLASERSTATUSRESPONSE_STATUS']._serialized_start=148
  _globals['_GETLASERSTATUSRESPONSE_STATUS']._serialized_end=173
  _globals['_SETBIASVOLTAGEREQUEST']._serialized_start=175
  _globals['_SETBIASVOLTAGEREQUEST']._serialized_end=215
  _globals['_SETBIASVOLTAGERESPONSE']._serialized_start=217
  _globals['_SETBIASVOLTAGERESPONSE']._serialized_end=258
  _globals['_ENABLELASERREQUEST']._serialized_start=260
  _globals['_ENABLELASERREQUEST']._serialized_end=280
  _globals['_ENABLELASERRESPONSE']._serialized_start=282
  _globals['_ENABLELASERRESPONSE']._serialized_end=320
  _globals['_DISABLELASERREQUEST']._serialized_start=322
  _globals['_DISABLELASERREQUEST']._serialized_end=343
  _globals['_DISABLELASERRESPONSE']._serialized_start=345
  _globals['_DISABLELASERRESPONSE']._serialized_end=367
  _globals['_LASERCONTROLSERVICE']._serialized_start=370
  _globals['_LASERCONTROLSERVICE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
